name: rollbar-client
version: 0.1.0
github: "stackbuilders/rollbar-haskell"
license: MIT
author: "Stack Builders Inc."
maintainer: "Sebastián Estrella <sestrella@stackbuilders.com>"
copyright: "2020 Stack Builders Inc."

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Core library to communicate with Rollbar API.
# category:            Web

description: |
  Please see the README on GitHub at
  <https://github.com/stackbuilders/rollbar-haskell/tree/master/rollbar-client>

dependencies:
  - base >= 4.12 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.4 && < 2
    - bytestring
    - directory
    - exceptions >= 0.10 && < 1
    - mtl >= 2.2 && < 3
    - req >= 2.1 && < 4
    - text

executables:
  simple:
    source-dirs: examples/simple
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - rollbar-client

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - hspec >= 2.7 && < 3
      - req
      - rollbar-client
    build-tools:
      - hspec-discover:hspec-discover >= 2.7 && < 3
