name:                rollbar-wai
version:             0.1.0
github:              "githubuser/rollbar-wai"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rollbar-wai#readme>

dependencies:
  - base >= 4.12 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.4 && < 2
    - bytestring
    - case-insensitive >= 1.2 && < 2
    - http-types >= 0.12 && < 1
    - rollbar-client >= 0.1 && < 1
    - text
    - unordered-containers >= 0.2 && < 1
    - wai >= 3.2 && < 4
    - wai-extra >= 3.0 && < 4

executables:
  warp:
    source-dirs: examples/warp
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - rollbar-client
      - rollbar-wai
      - wai
      - warp

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rollbar-wai
