---
version: 2.1

commands:
  setup_haskell:
    parameters:
      cabal:
        type: string
        default: "3.2"
      ghc:
        type: string

    steps:
      - run: apt update
      - run: apt install -y ca-certificates curl git gnupg zlib1g-dev
      - run: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574
      - run: echo 'deb http://downloads.haskell.org/debian buster main' > /etc/apt/sources.list.d/haskell.list
      - run: apt update
      - run: apt install -y cabal-install-<< parameters.cabal >> ghc-<< parameters.ghc >>
      - run: echo 'export PATH=/opt/ghc/bin:$PATH' >> $BASH_ENV

  cabal_build:
    steps:
      - run: cabal update
      - run: cabal configure --enable-tests -fexample
      - run: cabal build all --only-dependencies
      - run: cabal build all
      - run: cabal test all

  stack_build:
    steps:
      - run: apt update
      - run: apt install -y curl
      - run: stack update
      - run: stack build --only-dependencies --test
      - run: stack build --test --no-run-tests
      - run: stack test

jobs:
  cabal_8_10:
    docker:
      - image: debian:10

    steps:
      - checkout
      - setup_haskell:
          ghc: "8.10.2"
      - cabal_build

  cabal_8_8:
    docker:
      - image: debian:10

    steps:
      - checkout
      - setup_haskell:
          ghc: "8.8.4"
      - cabal_build

  cabal_8_6:
    docker:
      - image: debian:10

    steps:
      - checkout
      - setup_haskell:
          ghc: "8.6.5"
      - cabal_build

  stack_16:
    docker:
      - image: fpco/stack-build-small:lts-16.17

    steps:
      - checkout
      - stack_build

  stack_14:
    docker:
      - image: fpco/stack-build-small:lts-14.27

    steps:
      - checkout
      - stack_build

workflows:
  main:
    jobs:
      - cabal_8_10
      - cabal_8_8
      - cabal_8_6
      - stack_16
      - stack_14
